<?php
///Generate script
				echo"<center><b>Select, copy and paste this html script in the TEXT mode of your post.</b><br></center>";
				$tableHead="<h3>Total Comments on this blog in $month $date2</h3><ol>";	
				$tbData="";
				$countAuthors=0;
				$countComments=0;
				$pageBreakCounter=0;
				foreach( $result as $gCom) //=mysql_fetch_object($result))
					{
						$countAuthors++;
						$pageBreakCounter++;

						$url=$gCom->URL;
						////Set the nofollow tag
						if(($gCom->NumCom >= $ltype) AND ($ltype > 0))
							{
								$dof="";
							}
								else
							{
								$dof="rel=\"nofollow\"";
							}
						if(empty($url))
							{
								$author=$gCom->Commentator;
							}
								else
							{
								$author="<a href=\"".$gCom->URL."\" target=\"_blank\" $dof>".$gCom->Commentator."</a>";
							}
							$r=rand(1,2);
							if($r==1)
								{
									$rt="dropped";
								}
									else
								{
									$rt="made";
								}
							//////////////////
							if($gCom->NumCom > 1 )
								{
									$s="s";
								}
									else
								{
									$s="";
								}
					if($pageBreakCounter == $PageBreak)
							{
								////Add page break and reset counter
				$tbData.="</ol><b>Click The Page Number Below To Continue</b><br>
				<!--nextpage--><h3>Total Comments on this blog in $month $date2</h3> <br>List Continues</b><br><ol>";
								$pageBreakCounter=0;
							}

						$tbData.="<li>$author $rt <b>".$gCom->NumCom." comment".$s."</b></li>";
						
						$countComments=$countComments+$gCom->NumCom;
					}
					$html=$tableHead;
					$html.=$tbData;
					$html.="</ol>
						<br><b>$countAuthors</b> comment authors with <b>$countComments</b> comments in the month of <b>$month $date2</b>
						<br><i>This list was generated by <a href=\"http://enstinemuki.com/my-comment-authors\" target=\"_blank\">MyCommentAuthors</a></i>";
					echo"<center><textarea cols=\"70\" rows=\"20\">$html</textarea><br><br>
					<a href=\"options-general.php?page=".$_GET['page']."&MailTo=$date1&n=$date2&m=$month&count=$countAuthors\">
					<img src=\"" .plugins_url( 'images/maillist.gif' , __FILE__ ). "\" border=\"0\"> </a></center>";
?>